#ifndef _CONFIG_H_8CH_MOSFET_REVA
#define _CONFIG_H_8CH_MOSFET_REVA

#define HARDWARE_VERSION "8CH-MOSFET-REV-A"

#define BUS_VOLTAGE_ESP32
#define BUS_VOLTAGE_R1 100000
#define BUS_VOLTAGE_R2 10000
#define BUS_VOLTAGE_PIN 36

#endif // _CONFIG_H_8CH_MOSFET_REVA